### ISSUE TITLE
binary-security-check command line invalid arguments

### ISSUE THREAD

**Issue by memrekaraaslan** [koutheir/binary-security-check#2]
I am trying to run the binary after installing it on my system(Linux Ubuntu), but I get an invalid arguments error. How to use this binary correctly? Can you help me for this?

My usage:
(In my home directory):
cd .cargo/bin
./binary-security-check -l MYFILE

**Comment by koutheir** [comment]
# Options syntax clarification

It seems to me that you're confused about the command line syntax:
```
binary-security-check [-v] [-c COLOR] [(-s DIR | -l FILE | -i SPEC)] <file>...
```

The `[ ]` mean that what is inside them is optional, i.e., it can be omitted. The `(x | y | z)` mean that you have to specify only one of `x`, `y` or `z`. Therefore, the `[(-s DIR | -l FILE | -i SPEC)]` mean that you can specify either `-s DIR`, or `-l FILE`, or `-i SPEC`, or **nothing**. After that, you have to specify the file(s) to analyze, as indicated by `<file>...`.

You command line should then become simply:
```
 ./binary-security-check MYFILE
```
# Example

However, depending on the binary, you might get an error `Dependent C runtime library is not recognized.`. For example:
```
$ binary-security-check /usr/bin/ls
14:26:03 [ERROR] /usr/bin/ls: Dependent C runtime library is not recognized.
```

You can, if the binary can run on the host, use the `ldd` tool to determine which C library is needed by the binary. For example:
```
$ ldd /usr/bin/ls
        linux-vdso.so.1 (0x00007ffdb2fbe000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f43d7cbf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f43d7afc000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f43d7a6c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f43d7a67000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f43d7d3b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f43d7a46000)
```
which indicates that `/lib/x86_64-linux-gnu/libc.so.6` is the C library is needed by `/usr/bin/ls`.
> If the binary you're analyzing does not run on the host (e.g., cross-compiled to another architecture) then you can use the `readelf` tool to determine the C library file name (or partial path), and then given the *sysroot* or the target platform, find the C library needed by that program.

Now giving the `-l` to `binary-security-check` produces the following output (minus the colors):
```
$ binary-security-check -l /lib/x86_64-linux-gnu/libc.so.6 /usr/bin/ls
/usr/bin/ls: +ASLR +STACK-PROT +READ-ONLY-RELOC !IMMEDIATE-BIND ~FORTIFY-SOURCE(+printf,+memcpy,+sprintf,+snprintf,+fprintf,!snprintf,!mempcpy,!memset,!mbstowcs,!readlink,!gethostname,!memcpy,!stpncpy,!memmove,!wcstombs,!getcwd,!strcpy)
```

**Comment by memrekaraaslan** [comment]
It's work. Thanks for speedy reply. 

> hie@ubuntu:~/.cargo/bin$ ldd /usr/bin/lzma
>         linux-vdso.so.1 =>  (0x00007ffd701b8000)
>         liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f2e7e06a000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2e7dca0000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2e7da9c000)
>         /lib64/ld-linux-x86-64.so.2 (0x00005628e072a000)
> hie@ubuntu:~/.cargo/bin$ ./binary-security-check -l /lib/x86_64-linux-gnu/libc.so.6 /usr/bin/lzma
> /usr/bin/lzma: !ASLR +STACK-PROT +READ-ONLY-RELOC !IMMEDIATE-BIND ~FORTIFY-SOURCE(+snprintf,+vfprintf,+vsnprintf,+fprintf,+printf,!memcpy,!read)
> 

This output is true, I think. 
Finally I want to ask one more thing. I want to run this command line utility on my ARM device. Is this also possible?

**Comment by koutheir** [comment]
I just updated the tool documentation to help with issues like this one.

> I want to run this command line utility on my ARM device. Is this also possible?

If you want to analyze ARM binaries, then you can:
- Either run the tool directly on ARM binaries located on your computer. You'll probably need either the ARM device sysroot, or network access to the device's root directory. You can use `SSHFS` for example to give access, on your computer, to the ARM binaries located on the ARM device.
- or you can build the tool and run it on an ARM device directly. The tool is fairly portable to architectures supported by Rust, which include ARM.

For example, installing a Rust toolchain on an ARM device might look [like this](https://www.rust-lang.org/tools/install):
```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
...
$ source $HOME/.cargo/env
```

Due to some dependencies, in order to build the tool, one should install a C compiler toolchain. For example (on the device):
```
$ sudo pacman -S gcc
...
```

Then, the tool can be installed per usual command (on the device):
```
$ cargo install --git 'https://github.com/koutheir/binary-security-check.git'
...
```

This allows running the tool directly on the device, for instance:
```
$ binary-security-check /usr/bin/bash
/usr/bin/bash: +ASLR +STACK-PROT +READ-ONLY-RELOC +IMMEDIATE-BIND ~FORTIFY-SOURCE(+strncpy,+memmove,+memcpy,+strcpy,+asprintf,+longjmp,+snprintf,+vsnprintf,+fdelt,+vfprintf,+printf,+fprintf,+sprintf,!mbstowcs,!memmove,!memset,!mbsnrtowcs,!fgets,!confstr,!wcsrtombs,!getgroups,!wcrtomb,!stpcpy,!wctomb,!read,!memcpy,!strcpy,!readlink,!mbsrtowcs,!strcat,!strncpy,!getcwd,!gethostname)
```

**Comment by memrekaraaslan** [comment]
Hello again.

I followed that you said, I have ARM machine and Yocto operating system. 
I installed Rust toolchain on my board, then I tried installing the C compiler but the "pacman" command could not be found. 

```
root@imx6ul-var-dart:~# sudo pacman -S gcc
-sh: sudo: not found
root@imx6ul-var-dart:~# pacman -S gcc
-sh: pacman: not found
root@imx6ul-var-dart:~# cargo install --git 'https://github.com/koutheir/binary-security-check.git'
    Updating git repository `https://github.com/koutheir/binary-security-check.git`
  Installing binary-security-check v1.0.2 (https://github.com/koutheir/binary-security-check.git#ff8cfa4e)
    Updating crates.io index
  Downloaded memmap v0.7.0
  Downloaded serde v1.0.110
  Downloaded termcolor v1.1.0
  Downloaded failure v0.1.8
  Downloaded log v0.4.8
  Downloaded docopt v1.1.0
  Downloaded regex v1.3.7
  Downloaded rayon v1.3.0
  Downloaded lazy_static v1.4.0
  Downloaded serde_derive v1.0.110
  Downloaded scroll v0.10.1
  Downloaded simplelog v0.7.6
  Downloaded strsim v0.9.3
  Downloaded memchr v2.3.3
  Downloaded crossbeam-deque v0.7.3
  Downloaded aho-corasick v0.7.10
  Downloaded rayon-core v1.7.0
  Downloaded thread_local v1.0.1
  Downloaded goblin v0.2.3
  Downloaded failure_derive v0.1.8
  Downloaded regex-syntax v0.6.17
  Downloaded cfg-if v0.1.10
  Downloaded backtrace v0.3.47
  Downloaded either v1.5.3
  Downloaded libc v0.2.70
  Downloaded proc-macro2 v1.0.12
  Downloaded synstructure v0.12.3
  Downloaded syn v1.0.21
  Downloaded chrono v0.4.11
  Downloaded maybe-uninit v2.0.0
  Downloaded term v0.6.1
  Downloaded scroll_derive v0.10.2
  Downloaded crossbeam-epoch v0.8.2
  Downloaded quote v1.0.5
  Downloaded num_cpus v1.13.0
  Downloaded crossbeam-queue v0.2.1
  Downloaded crossbeam-utils v0.7.2
  Downloaded plain v0.2.3
  Downloaded object v0.19.0
  Downloaded time v0.1.43
  Downloaded dirs v2.0.2
  Downloaded unicode-xid v0.2.0
  Downloaded rustc-demangle v0.1.16
  Downloaded addr2line v0.12.0
  Downloaded num-integer v0.1.42
  Downloaded num-traits v0.2.11
  Downloaded autocfg v1.0.0
  Downloaded memoffset v0.5.4
  Downloaded scopeguard v1.1.0
  Downloaded dirs-sys v0.3.4
  Downloaded gimli v0.21.0
   Compiling autocfg v1.0.0
   Compiling libc v0.2.70
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: failed to compile `binary-security-check v1.0.2 (https://github.com/koutheir/binary-security-check.git#ff8cfa4e)`, intermediate artifacts can be found at `/tmp/cargo-installqWS75j`

Caused by:
  could not compile `libc`.

To learn more, run the command again with --verbose.
```

**Comment by koutheir** [comment]
>  I installed Rust toolchain on my board, then I tried installing the C compiler but the "pacman" command could not be found.

The `pacman` command was just an example of how to install a package on your board if it was running ArchLinuxARM. It is the equivalent of `apt-get` on Debian or Ubuntu. I have no idea which package manager (if any) is managing your Yocto system. If you don't have any package managers on your Yocto system, then you might need to include it in another way, such as regenerating your Yocto system from a configuration that includes GCC.

> ```
> error: linker `cc` not found
>   |
>   = note: No such file or directory (os error 2)
> ```

This is due to the C compiler missing on your board. That is the reason why you should install GCC.

**Comment by memrekaraaslan** [comment]
I have placed the binary-security-check binary file on my Ubuntu machine with x86_64 architecture on my ARM device with ssh. When I run it, I got an output like the one below

```
root@imx6ul-var-dart:~# ./binary-security-check /usr/bin/bash
./binary-security-check: line 2: syntax error: unexpected word (expecting ")")
```

If I cannot solve it otherwise, I should add the c compiler toolchain when building the image in Yocto. So I guess I should run a C compiler on the ARM device. Or can I compile the binary file on my ubuntu machine according to ARM and transfer it to the device with ssh?

**Comment by koutheir** [comment]
> When I run it, I got an output like the one below

Binaries built for Linux/amd64 do not run on Linux/arm. You need to build a binary for Linux/arm, either by building on the device, or by cross-compiling it on your host. I think the easiest way is to build it on the device.

> I should add the c compiler toolchain when building the image in Yocto.

Yes.

> Or can I compile the binary file on my ubuntu machine according to ARM and transfer it to the device with ssh?

It is theoretically possible to cross-compile Rust code to an architecture different from your host (arm vs amd64), but I didn't attempt to do that, because I think it is harder to set up.

**Comment by koutheir** [comment]
Back to the issue of cross compiling for ARMv7-A. With the latest version, I advise to cross-compile for ARMv7-A on an AMD64 Linux, but instead of targeting the usual target `armv7-unknown-linux-gnueabihf`, it's easier to target `armv7-unknown-linux-musleabihf`, which would make the resulting binary self-contained. For example:
```
# On an Ubuntu Linux for amd64, where rustup has already been installed...
$ sudo apt-get install clang lld musl-dev
$ rustup target add armv7-unknown-linux-musleabihf
$ cargo build --release --target=armv7-unknown-linux-musleabihf
```
