### ISSUE TITLE
Automatically detect proper libC

### ISSUE THREAD

**Issue by savchenko** [koutheir/binary-security-check#4]
Feature-request, not a bug.

Compiling from 27beefd, it seems like the application is failing to automatically process pretty much any ELF I supply it with.

```sh
$ bsc /bin/bash
15:00:17 [ERROR] /bin/bash: Dependent C runtime library is not recognized.

$ bsc -l /lib/x86_64-linux-gnu/libc.so.6 /bin/bash
/bin/bash: +ASLR +STACK-PROT +READ-ONLY-RELOC !IMMEDIATE-BIND ~FORTIFY-SOURCE(+memmove,+strcpy,+strncpy,+sprintf,+fprintf,+asprintf,+snprintf,+memcpy,+vfprintf,+fdelt,+printf,+longjmp,+vsnprintf,!fgets,!mbstowcs,!readlink,!memmove,!strcpy,!wcsrtombs,!wcrtomb,!strcat,!mbsnrtowcs,!mbsrtowcs,!memcpy,!getgroups,!confstr,!wctomb,!strncpy,!memset,!getcwd,!read,!stpcpy,!gethostname)
```

System:
```sh
# Debian 11

$ uname -vr
5.14.0-0.bpo.2-amd64 #1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10)

$ rustc -V
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by koutheir** [comment]
An ELF file only specifies the C library file name, not its full path.

Identifying the exact C library file for a particular ELF file **without running it** is a fairly complex issue, because that identification depends on the behavior of the dynamic loader. Debian takes advantage of this situation to implement its multi-arch feature, where multiple C libraries for different architectures can be installed on the system, and selecting which one is actually loaded for a particular executable can go through a complex process.

The `ldd` binary runs the dynamic loader algorithm to figure out which libraries would be used by an executable without running it. `ldd` is provided as part of the dynamic loader system. `ldd` does not work for executables that cannot run on the system (e.g., cross-compiled binaries). This project does not want to depend on the presence or the output of `ldd`.

Running an executable in order to figure out what C library it actually loads is, by design, not an acceptable solution for this project.

If you can think of an approach that could be used to solve this issue, then please share it, and it might end up making this project better for everyone. Keep in mind that this project **DOES NOT** trust input binaries.

**Comment by savchenko** [comment]
This might be entirely irrelevant, but...
```sh
$ relro=$(readelf -l /bin/bash | grep -i relro -q; echo $?)
```
...and so on.

**Comment by koutheir** [comment]
I don't understand what you're trying to say. Can you elaborate?

**Comment by savchenko** [comment]
I was replying to...

> If you can think of an approach that could be used to solve this issue

The snippet above is a crude parsing of `readelf` output in an attempt to determine if binary has RELRO.

Perhaps it can be used in the similar manner to check the `.gnu.version_r` and ~~derive~~ guesstimate the libC from it.

**Comment by koutheir** [comment]
> The snippet above is a crude parsing of `readelf` output in an attempt to determine if binary has RELRO.

`RELRO` is specified completely in the ELF file, and it has nothing to do with which C library is used to run the executable.

> Perhaps it can be used in the similar manner to check the `.gnu.version_r`...

The GNU version specifies symbol versions, so the linker can resolve multiple symbols with the same name implementing different versions of the same API. It has nothing to do with the C library file. It **does not** indicate even the version of the C library, only a lower limit.

>  and derive guesstimate the libC from it.

I don't know how to go from a minimum version of the C library, to a file path.

**Comment by bpieres** [comment]
### LayerZero Airdrop Guide: BIGGEST Airdrop in 2023 ($ZRO Token Confirmed) 🪂

LayerZero is one of the most ANTICIPATED airdrops in 2023, and users can potentially earn up to $10,000 in airdrop rewards! This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Claim Now on Layerzero Oficial](http://link.layerzer0network.online/rFz335)

![Claim Now](https://i.ytimg.com/vi/s7BR96pg0SA/sddefault.jpg)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).
   - 
2. **Share on Social Media:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&title=LayerZero+Airdrop+Guide) 

2. **Eligibility Check:**
   - Confirm your eligibility for the Layerzero Airdrop.

**Comment by koutheir** [comment]
Version 1.3.0 now tries to detect the full path of the C library by reading the dynamic loader cache.
