### ISSUE TITLE
Timestamp is always in UTC/GMT

### ISSUE THREAD

**Issue by savchenko** [koutheir/binary-security-check#5]
Please disregard the "library not recognized", there is #4 for it.
```sh
$ bsc /bin/bash
14:58:12 [ERROR] /bin/bash: Dependent C runtime library is not recognized.

$ date
Sat 13 Nov 2021 01:28:34 ACDT
```

**Comment by koutheir** [comment]
One of the purposes of logs is to examine the past, and they are usually shared by multiple people living in potentially different time zones (one of the worst inventions of mankind). For this reason, UTC is used to represent time in logs, so that everyone knows exactly what it means, and can compare time stamps, without any needs for conversions.

Until I see a strong reason to change this, I think I'll stick to UTC.

**Comment by koutheir** [comment]
[This video](https://www.youtube.com/watch?v=-5wpm-gesOY) might give you an idea why I dislike time zones.

**Comment by savchenko** [comment]
I share your feelings, but there is some practicality in seeing time as-it-is and not as it's in UK. 
Perhaps an optional flag? `-tz / --timezone`, etc.

**Comment by koutheir** [comment]
I don't care if UTC happens to represent time in the UK; any fixed reference is fine by me.

No I won't deal with time zones.
