### ISSUE TITLE
[QUESTION] Can this Analyze Static Binaries?

### ISSUE THREAD

**Issue by Azathothas** [koutheir/binary-security-check#7]
I have statically compiled binaries, that have no dynamically linked libc.

I get:
```bash
$ file "/home/runner/hugo/hugo"
/home/runner/hugo/hugo: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, stripped

$ ldd "/home/runner/hugo/hugo"
        statically linked

$ binary-security-check "/home/runner/hugo/hugo"
07:49:57 [ERROR] /home/runner/hugo/hugo: dependent C runtime library is not recognized.
```

I have been using [`OfriOuzan/HardeningMeter`](https://github.com/OfriOuzan/HardeningMeter) which works even for static binaries.
Could a similar feature-set be implemented in [`binary-security-check`](https://github.com/koutheir/binary-security-check) as well?

**Comment by koutheir** [comment]
Can you use the `--verbose` flag and provide the output of the tool here?

**Comment by koutheir** [comment]
The error message "dependent C runtime library is not recognized." is output because `binary-security-check` **does not** know which C library implementation has been statically linked into the binary (if any).

In this situation, you can help `binary-security-check` by indicating that the C library implementation that has been statically linked into the input binary conforms to one of the LSB (Linux Standard Base) standards. This allows `binary-security-check` to assume some information about the C library without the need to know what it is or where it is.

> Whether your C library implementation **actually** conforms to the specified LSB standard is not something that `binary-security-check` verifies.

For example, you can specify the parameter `--libc-spec`/`-i` with some version of the LSB standard (`--help` shows accepted values):

```shell
$ binary-security-check --libc-spec=lsb5 test/a
test/a: +ASLR !STACK-PROT +READ-ONLY-RELOC +IMMEDIATE-BIND ?FORTIFY-SOURCE()
```

For reference, the binary `test/a` was compiled from the file `test/a.c`:
```c
#include <stdio.h>

static char buffer[128];

int main() {
    sprintf(buffer, "Hello, %s", "world");
    puts(buffer);
    return 0;
}
```

and it was compiled with:
```shell
$ clang -O2 -static-pie -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -D_FORTIFY_SOURCE=2 -o test/a test/a.c
$ file test/a
test/a: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), static-pie linked, BuildID[sha1]=b4bc5eddf1a5c92c755058756874294e2ecd029c, for GNU/Linux 3.2.0, not stripped
```

**Comment by koutheir** [comment]
In order to make the error message more helpful in the future, I added a hint:
```shell
$ binary-security-check test/a
17:15:47 [ERROR] test/a: dependent C runtime library is not recognized. Consider specifying --sysroot, --libc or --libc-spec.
```

**Comment by koutheir** [comment]
> I have been using [OfriOuzan/HardeningMeter](https://github.com/OfriOuzan/HardeningMeter) which works even for static binaries.
> Could a similar feature-set be implemented in [binary-security-check](https://github.com/koutheir/binary-security-check) as well?

The `HardeningMeter` tool simply **hides the issue** from you instead of reporting it and asking you to decide what to do about it. The function [`get_glibc_fortify_functions`](https://github.com/OfriOuzan/HardeningMeter/blob/8c745f7606aff1db4cc9f2e5fea65d505193604c/Linux.py#L100) simply returns nothing if it cannot find the C library implementation, thus not providing any *useful information* about fortified functions.

My approach is different, in that, when `binary-security-check` needs information that you can specify (`--sysroot`, `--libc` or `--libc-spec`), in order to provide you with the security assertion, then `binary-security-check` errors out, instead of silently omitting the information. I understand that this choice may seem harsh, but this tool is intended to be used for security purposes, so this approach seems reasonable to me. Maybe I should implement a flag that allows skipping fortification assertions in order to avoid the need to recognize the C library implementation.

**Comment by koutheir** [comment]
> Maybe I should implement a flag that allows skipping fortification assertions in order to avoid the need to recognize the C library implementation.

Done. Starting from version 1.2.14, you can specify the flag `--no-libc`/`-n` in order to avoid probing for the C library. This means that cases where one cannot (or does not want to) locate the C library can also be checked. Furthermore, binaries that do not rely on any C library, e.g., assembler-only programs, can also be checked.
